import sys
import os
import asyncio

# Add the project root directory to the Python path
sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), '..')))

# The config import will automatically load dotenv and map variables!
from app.core.config import settings
from langchain_core.messages import HumanMessage
from app.agent.graph import app

async def main():
    print("--- Starting LangGraph Execution ---")
    
    # 1. Initialize the AgentState with the hardcoded test query
    initial_state = {
        "messages": [HumanMessage(content="What is the expense ratio and total assets for SPY?")],
        "working_ticker_symbols": ["SPY"],
        "query_intent": "" # Will be populated by the intent_classifier
    }
    
    print(f"\nInitial Query: '{initial_state['messages'][0].content}'")
    print("--------------------------------------------------\n")

    # 2. Invoke the graph and stream the state updates
    # We use astream() here (instead of ainvoke) because it specifically yields the state changes
    # at each individual node, allowing us to see the exact execution flow!
    async for event in app.astream(initial_state):
        for node_name, state_update in event.items():
            print(f">>> Execution Node: {node_name} <<<")
            
            # Print the intent if it was just classified
            if "query_intent" in state_update:
                print(f" -> Classified Intent: {state_update['query_intent']}")
                
            # Print any new messages generated by the node (e.g., tool results or final answer)
            if "messages" in state_update:
                for msg in state_update["messages"]:
                    print(f" -> Output: {msg.content[:500]}...\n") # Truncating for readability
                    
            print("-" * 50)

    print("\n--- Execution Finished ---")

if __name__ == "__main__":
    asyncio.run(main())
